@startuml snake

class Juego {
    -serpiente: Serpiente
    -tablero: Tablero
    +iniciarJuego(): void
    +terminarJuego(): void
}

class Serpiente {
    -cuerpo: Lista<Punto>
    -direccion: Direccion
    +mover(): void
    +cambiarDireccion(nuevaDireccion: Direccion): void
}

class Tablero {
    -ancho: int
    -alto: int
    +dibujar(): void
}

class Punto {
    -x: int
    -y: int
}

enum Direccion {
    ARRIBA
    ABAJO
    IZQUIERDA
    DERECHA
}

Juego --> Serpiente
Juego --> Tablero
Serpiente *-- Punto
Tablero *-- Punto

Serpiente "1" *-- "0..*" Punto
Tablero "1" *-- "0..*" Punto

@enduml