@startuml snake

class Game {
    -snake: Snake
    -board: Board
    +startGame(): void
    +endGame(): void
}

class Snake {
    -body: List<Point>
    -direction: Direction
    +move(): void
    +changeDirection(newDirection: Direction): void
}

class Board {
    -width: int
    -height: int
    +draw(): void
}

class Point {
    -x: int
    -y: int
}

enum Direction {
    UP
    DOWN
    LEFT
    RIGHT
}

Game --> Snake
Game --> Board
Snake *-- Point
Board *-- Point

Snake "1" *-- "0..*" Point
Board "1" *-- "0..*" Point

@enduml
